#!/bin/sh

cp -r ./src/ ./src_temp/
chown 1000:1000 ./src_temp/var/log/pamfingerprint.log

dpkg --build ./src_temp/ ./pamfingerprint.deb

rm -R ./src_temp/

chown 1000:1000 ./pamfingerprint.deb
exit "${?}"
