#!/bin/sh

if ( test "$1" = "remove" || test "$1" = "purge" ); then
    pam-auth-update --package --remove pamfingerprint
else

    pam-auth-update --package pamfingerprint

    chown 1000:1000 /var/log/pamfingerprint.log

fi

