#!/bin/sh

if ( test "$1" = "remove" || test "$1" = "purge" ); then
    find /usr/lib/pamfingerprint/ -type f -name *.pyc -exec rm {} \;
    find /usr/lib/python2.7/dist-packages/PyFingerprint/ -type f -name *.pyc -exec rm {} \;
fi
