#!/bin/sh

if ( test "${1}" = "remove" ); then
    ## Removes PAM configuration in "/etc/pam.d/common-auth":
    pam-auth-update --package --remove fingerprint
fi

## Deletes compiled Python files before removing package
find /usr/lib/pamfingerprint/ -type f -name *.pyc -exec rm {} \;

exit "${?}"
