.TH pam_fingerprint-conf 1 "" "" "PAM Fingerprint"

.SH NAME
pam_fingerprint-conf - PAM_Fingerprint configuration tool
.SH SYNOPSIS
.B pam_fingerprint-conf
.RI [ actions ]
.br

.SH DESCRIPTION
\fBPAM Fingerprint\fP is a open-source Unix PAM module that allows biometric fingerprint authentification for users.

It is totally written in python and uses a python framework called pam_python as adapter to implement the PAM interface that is written in C. PAM Fingerprint uses the Adafruit optical fingerprint sensor for biometric authentification. Pyserial, a python written library for serial connections, is used for the connection between the sensor and a computer. The sensor is connected with a USB TTL converter.
.PP

.SH ACTIONS

.IP --add-user
Adds a new user and enrolls new fingerprint image.

.IP --remove-user
Removes an user from fingerprint database.

.IP --check
Enrolls fingerprint and checks if user is valid.

.SH "SEE ALSO"
\fBUsed fingerprint sensor\fP: http://www.adafruit.com/products/751
.br 
\fBPyserial\fP: http://pyserial.sourceforge.net/
.br 
\fBpam_python\fP: http://ace-host.stuart.id.au/russell/files/pam_python/

.SH AUTHOR
This manual page was written by Philipp Meisberger <team@pm-codeworks.de>. Visit www.pm-codeworks.de for more interesting projects.