.TH pamfingerprint-conf 1 "" "" "PAM Fingerprint"

.SH NAME
pamfingerprint-conf - PAM Fingerprint configuration tool
.SH SYNOPSIS
.B pamfingerprint-conf
.RI [ actions ]
.br

.SH DESCRIPTION
\fBPAM Fingerprint\fP is an open-source Linux PAM module that allows biometric fingerprint authentication.

It is totally written in python and uses a python framework called pam_python to allow writing PAM modules in python instead in C. Pyserial, a python written library for serial connections, is used for the connection between the sensor and a computer. The sensor is connected with a USB TTL converter. pamfingerprint works with any application supporting PAM, for example su, sudo, etc.
.PP

.SH ACTIONS

.IP --add-user
Adds a new user.

.IP --remove-user
Removes an user.

.IP --update
Updates fingerprint for an existing user.

.IP --check
Checks fingerprint and returns if user exists.

.SH "SEE ALSO"
\fBUsed fingerprint sensor\fP: http://www.adafruit.com/products/751

\fBPyserial\fP: http://pyserial.sourceforge.net/

\fBpam_python\fP: http://ace-host.stuart.id.au/russell/files/pam_python/

.SH FILES
/etc/pam_fingerprint.conf
.br
/var/log/pam_fingerprint.log

.SH AUTHORS
Philipp Meisberger <team@pm-codeworks.de> 
.br
Bastian Raschke <>

Please report Bugs to one of those mail addresses. Visit www.pm-codeworks.de for more interesting projects.