#!/bin/sh

# Install PAM module
cp ../src/pam_fingerprint.so /lib/x86_64-linux-gnu/security/pam_fingerprint.so
chown root:root /lib/x86_64-linux-gnu/security/pam_fingerprint.so
chmod 644 /lib/x86_64-linux-gnu/security/pam_fingerprint.so

# Allocate PAM module to system
cp common-auth /etc/pam.d/
chmod 644 /etc/pam.d/common-auth
