.TH pamfingerprint-conf 1 "" "" "PAM Fingerprint"

.SH NAME
\fBpamfingerprint-conf\fP - \fBpamfingerprint\fP configuration program

.SH SYNOPSIS
.nf
.fam C
\fBpamfingerprint-conf\fP [\fB--add-user\fP NAME | \fB--remove-user\fP NAME | \fB--version\fP | \fB--help\fP]
.fam T
.fi

.SH DESCRIPTION
\fBpamfingerprint-conf\fP allows (as root) to bind or unbind users to \fBpamfingerprint\fR.

.SH OPTIONS
.TP
.B
\fB--add-user\fR NAME
Adds a new user.

.TP
.B
\fB--remove-user\fR NAME
Removes a user.

.TP
.B
\fB--version\fR
Prints version and exits.

.TP
.B
\fB--help\fR, \fB-h\fR
Show summary of options.
.PP

.SH "SEE ALSO"
\fBpamfingerprint\fR(1), \fBpamfingerprint-check\fR(1)

.SH FILES
/etc/pamfingerprint.conf

.SH AUTHORS
Philipp Meisberger <team@pm-codeworks.de> 
.br
Bastian Raschke <bastian.raschke@posteo.de>

Please send bug reports to one of those mail addresses. Visit www.pm-codeworks.de and www.sicherheitskritisch.de for more interesting projects.
