.TH pamfingerprint-check 1 "March 2014" "" "PAM Fingerprint"

.SH NAME
\fBpamfingerprint-check\fP - pamfingerprint simulation program

.SH SYNOPSIS
.nf
.fam C
\fBpamfingerprint-check\fP \fB--check-user\fP NAME | [\fB--version\fP | \fB--help\fP]
.fam T
.fi

.SH DESCRIPTION
\fBpamfingerprint-check\fP can be used to simulate fingerprint authentication process for bind users.

.SH OPTIONS

.TP
.B
\fB--check-user\fR NAME
Runs check for an existing user.

.TP
.B
\fB--version\fR
Prints version and exits.

.TP
.B
\fB--help\fR, \fB-h\fR
Show summary of options.

.SH FILES
/etc/pamfingerprint.conf

.SH AUTHORS
Philipp Meisberger <team@pm-codeworks.de> 
.br
Bastian Raschke <bastian.raschke@posteo.de>

Please send bug reports to one of those mail addresses. Visit www.pm-codeworks.de and www.sicherheitskritisch.de for more interesting projects.