#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
PAM Fingerprint

Copyright 2014 Philipp Meisberger, Bastian Raschke.
All rights reserved.
"""

import hashlib
import time
import argparse
import os
import pamfingerprint.Config as Config
import pamfingerprint.__version__ as VERSION
import PyFingerprint.PyFingerprint as PyFingerprint


class PamFingerprint(object):
    """
    Configuration program.

    The PyFingerprint instance
    @var PyFingerprint __fingerprint

    Config instance
    @var Config __config
    """
    __fingerprint = None
    __config = None

    def __init__(self):
        """
        Constructor

        """

        ## Tries to init config instance
        try:
            self.__config = Config('/etc/pamfingerprint.conf')

        except Exception as e:
            print '[Exception] ' + e.message
            exit(1)

        ## Gets connection values
        port = self.__config.readString('PyFingerprint', 'port')
        baudRate = self.__config.readInteger('PyFingerprint', 'baudRate')
        address = self.__config.readHex('PyFingerprint', 'address')
        password = self.__config.readHex('PyFingerprint', 'password')

        ## Tries to establish connection
        try:
            self.__fingerprint = PyFingerprint(port, baudRate, address, password)

            if ( self.__fingerprint.verifyPassword() == False ):
                raise ValueError('The given fingerprint sensor password is wrong!')

        except Exception as e:
            print '[Exception] The fingerprint sensor could not be initialized: ' + e.message
            exit(1)

    def __showConfirmationDialog(self, question = ''):
        """
        Shows confirmation dialog.

        @param string question
        @return boolean
        """

        answer = raw_input(question + ' (Y/n)')

        if ( answer not in ['y', 'Y', ''] ):
            return False
        else:
            return True

    def addUser(self, userName):
        """
        Enrolls new fingerprint template and adds user to pamfingerprint.

        @param string userName
        @return boolean
        """

        ## Checks if user is root
        if ( os.geteuid() != 0 ):
            print '[Error] You need to have root privileges to add a user!'
            return False

        ## Checks if the the user is not already added
        if ( self.__config.itemExists('Users', userName) == True ):
            print '[Error] The user "' + userName + '" is already added!'
            return False

        ## Confirmation dialog
        if ( self.__showConfirmationDialog('Are you sure you want to add the user "' + userName + '"?') == False ):
            print 'Adding user canceled.'
            return False

        ## Tries to create new template for user
        try:
            freePositionNumber = -1

            ## Gets a boolean list for templates 0-255 indicating the used status
            templates = self.__fingerprint.getTemplateIndex(0)

            ## Tries to find free position for storing template
            for i in range(len(templates)):
                if ( templates[i] == False ):
                    freePositionNumber = i
                    break

            if ( freePositionNumber == -1 ):
                raise Exception('Could not find a free position for storing template!')

            print 'Waiting for finger...'

            while ( self.__fingerprint.readImage() == False ):
                pass

            self.__fingerprint.convertImage(0x01)

            ## Checks if template of read finger already exist
            result = self.__fingerprint.searchTemplate()
            positionNumber = result[0]

            ## Template does not exist
            if ( positionNumber == -1 ):
                print 'Remove finger...'
                time.sleep(2)

                print 'Waiting for same finger again...'

                while ( self.__fingerprint.readImage() == False ):
                    pass

                self.__fingerprint.convertImage(0x02)

                ## Creates new template
                self.__fingerprint.createTemplate()

                ## Stores new template on free position
                self.__fingerprint.storeTemplate(freePositionNumber)
                print 'Stored new template on position #' + str(freePositionNumber) + '.'
            else:
                print '[Warning] The finger already exists at template position #' + str(positionNumber) + '!'

                if ( self.__showConfirmationDialog('Bind this template to the user "' + userName + '" ?') == False ):
                    print 'Adding user canceled.'
                    return False
                else:
                    freePositionNumber = positionNumber

            ## Gets characteristics and calculates hash
            self.__fingerprint.loadTemplate(freePositionNumber, 0x01)
            characteristics = self.__fingerprint.downloadCharacteristics(0x01)
            fingerprintHash = hashlib.sha256(str(characteristics)).hexdigest()

            ## The new user information list
            userData = (
                str(freePositionNumber),
                fingerprintHash,
            )

            ## Adds user to configuration file
            self.__config.writeList('Users', userName, userData)

            if ( self.__config.save() == True ):
                print 'The user "' + userName + '" has been added successfully!'
            else:
                raise Exception('The configuration could not be written!')

        except Exception as e:
            print '[Exception] Error while adding user: ' + e.message
            return False

        return True

    def removeUser(self, userName):
        """
        Removes fingerprint template from sensor and removes user from configuration.

        @param string userName
        @return boolean
        """

        ## Checks if user is root
        if ( os.geteuid() != 0 ):
            print '[Error] You need to have root privileges to add a user!'
            return False

        ## Checks if the the user was already added
        if ( self.__config.itemExists('Users', userName) == False ):
            print '[Error] The user "' + userName + '" is not added!'
            return False

        ## Tries to get user information (template position, fingerprint hash)
        try:
            userData = self.__config.readList('Users', userName)

            ## Validates user information
            if ( len(userData) != 2 ):
                raise Exception('The user information of "' + userName + '" is invalid!')

            positionNumber = int(userData[0])
            expectedFingerprintHash = userData[1]

        except Exception as e:
            print '[Exception] ' + e.message
            return False

        ## Confirmation dialog
        if ( self.__showConfirmationDialog('Are you sure you want to remove the user "' + userName + '"?') == False ):
            print 'Removing user canceled.'
            return False

        ## Tries to delete template
        try:
            ## Gets characteristics
            self.__fingerprint.loadTemplate(positionNumber, 0x01)
            characteristics = self.__fingerprint.downloadCharacteristics(0x01)

            ## Calculates hash of template
            fingerprintHash = hashlib.sha256(str(characteristics)).hexdigest()

            ## Checks if template hash matches stored hash
            if ( fingerprintHash == expectedFingerprintHash ):
                self.__fingerprint.deleteTemplate(positionNumber)
                print 'Removed template on position #' + str(positionNumber) + '.'
            else:
                raise Exception('The template could not be found!')

            ## Removes entries from configuration file
            if ( self.__config.remove('Users', userName) == True and self.__config.save() == True ):
                print 'The user "' + userName + '" has been removed successfully!'
            else:
                raise Exception('The configuration file could not be written!')

        except Exception as e:
            print '[Exception] Error while removing user: ' + e.message
            return False

        return True


if ( __name__ == '__main__' ):

    parser = argparse.ArgumentParser(description='pamfingerprint configuration program:')

    parser.add_argument('--add-user', metavar='NAME', help='Adds a new user.')
    parser.add_argument('--remove-user', metavar='NAME', help='Removes a user.')
    parser.add_argument('--version', '-v', action='version', version='pamfingerprint '+ VERSION, help='Prints version and exits.')

    args = vars(parser.parse_args())

    if ( args['add_user'] ):
        PamFingerprint().addUser(args['add_user'])
    elif ( args['remove_user'] ):
        PamFingerprint().removeUser(args['remove_user'])
    else:
        parser.print_help()
