#!/bin/sh

# Install PAM module
cp ../src/lib/security/pam_fingerprint.py /lib/security/

cp ../src/etc/pam_fingerprint.conf /etc/
#chmod 600 /etc/pam_fingerprint.conf

cp ../src/var/log/pam_fingerprint.log /var/log/
chown phil: /var/log/pam_fingerprint.log
chmod 644 /var/log/pam_fingerprint.log

# Allocate PAM module to system
cp common-auth /etc/pam.d/
