"""
"" PyFingerprint
""
"" Copyright 2014 Bastian Raschke, Philipp Meisberger.
"" All rights reserved.
"""

## Enables debug mode
##
DEBUG = False


## Baotou start byte
FINGERPRINT_STARTCODE = 0xEF01

## Packet identification
##

FINGERPRINT_COMMANDPACKET = 0x01
FINGERPRINT_DATAPACKET = 0x02
FINGERPRINT_ACKPACKET = 0x07
FINGERPRINT_ENDDATAPACKET = 0x08

## Instruction codes
##

FINGERPRINT_VERIFYPASSWORD = 0x13
FINGERPRINT_SETPASSWORD = 0x12
FINGERPRINT_SETADDRESS = 0x15
FINGERPRINT_TEMPLATECOUNT = 0x1D

FINGERPRINT_GETIMAGE = 0x01
FINGERPRINT_IMAGE2TZ = 0x02

FINGERPRINT_REGMODEL = 0x05
FINGERPRINT_STORE = 0x06

FINGERPRINT_DELETECHAR = 0x0C
FINGERPRINT_EMPTY = 0x0D

FINGERPRINT_SEARCH = 0x04

## Packet reply confirmations
##

FINGERPRINT_OK = 0x00
FINGERPRINT_PACKETRECIEVEERR = 0x01

FINGERPRINT_PASSFAIL = 0x13

FINGERPRINT_INVALIDREG = 0x1A

FINGERPRINT_NOFINGER = 0x02
FINGERPRINT_IMAGEFAIL = 0x03

FINGERPRINT_UPLOADFAIL = 0x0F

FINGERPRINT_PACKETRESPONSEFAIL = 0x0E

FINGERPRINT_IMAGEMESS = 0x06
FINGERPRINT_FEATUREFAIL = 0x07
FINGERPRINT_INVALIDIMAGE = 0x15

FINGERPRINT_ENROLLMISMATCH = 0x0A

FINGERPRINT_UPLOADFEATUREFAIL = 0x0D

FINGERPRINT_BADLOCATION = 0x0B
FINGERPRINT_FLASHERR = 0x18

FINGERPRINT_DBRANGEFAIL = 0x0C

FINGERPRINT_DELETEFAIL = 0x10

FINGERPRINT_DBCLEARFAIL = 0x11

FINGERPRINT_NOMATCH = 0x08

FINGERPRINT_NOTFOUND = 0x09

## General error codes
##

FINGERPRINT_ADDRCODE = 0x20
FINGERPRINT_PASSVERIFY = 0x21

FINGERPRINT_TIMEOUT = 0xFF
FINGERPRINT_BADPACKET = 0xFE
